// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: pkg/structures/schedule/schedule.proto

package schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GclConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*ConfigMap           `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GclConfiguration) Reset() {
	*x = GclConfiguration{}
	mi := &file_pkg_structures_schedule_schedule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GclConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GclConfiguration) ProtoMessage() {}

func (x *GclConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_schedule_schedule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GclConfiguration.ProtoReflect.Descriptor instead.
func (*GclConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_structures_schedule_schedule_proto_rawDescGZIP(), []int{0}
}

func (x *GclConfiguration) GetConfigs() []*ConfigMap {
	if x != nil {
		return x.Configs
	}
	return nil
}

type ConfigMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodePort      string                 `protobuf:"bytes,1,opt,name=NodePort,proto3" json:"NodePort,omitempty"` //nodeId.PortId
	Sched         *Schedule              `protobuf:"bytes,2,opt,name=Sched,proto3" json:"Sched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMap) Reset() {
	*x = ConfigMap{}
	mi := &file_pkg_structures_schedule_schedule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMap) ProtoMessage() {}

func (x *ConfigMap) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_schedule_schedule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMap.ProtoReflect.Descriptor instead.
func (*ConfigMap) Descriptor() ([]byte, []int) {
	return file_pkg_structures_schedule_schedule_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigMap) GetNodePort() string {
	if x != nil {
		return x.NodePort
	}
	return ""
}

func (x *ConfigMap) GetSched() *Schedule {
	if x != nil {
		return x.Sched
	}
	return nil
}

type Schedule struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GatingCycle    float32                `protobuf:"fixed32,1,opt,name=GatingCycle,json=gating-cycle,proto3" json:"GatingCycle,omitempty"`
	TrafficClasses []*TrafficClass        `protobuf:"bytes,2,rep,name=TrafficClasses,json=traffic-classes,proto3" json:"TrafficClasses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_pkg_structures_schedule_schedule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_schedule_schedule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_pkg_structures_schedule_schedule_proto_rawDescGZIP(), []int{2}
}

func (x *Schedule) GetGatingCycle() float32 {
	if x != nil {
		return x.GatingCycle
	}
	return 0
}

func (x *Schedule) GetTrafficClasses() []*TrafficClass {
	if x != nil {
		return x.TrafficClasses
	}
	return nil
}

type TrafficClass struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	AssignedPortion int32                  `protobuf:"varint,2,opt,name=AssignedPortion,json=assigned-portion,proto3" json:"AssignedPortion,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrafficClass) Reset() {
	*x = TrafficClass{}
	mi := &file_pkg_structures_schedule_schedule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficClass) ProtoMessage() {}

func (x *TrafficClass) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_schedule_schedule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficClass.ProtoReflect.Descriptor instead.
func (*TrafficClass) Descriptor() ([]byte, []int) {
	return file_pkg_structures_schedule_schedule_proto_rawDescGZIP(), []int{3}
}

func (x *TrafficClass) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrafficClass) GetAssignedPortion() int32 {
	if x != nil {
		return x.AssignedPortion
	}
	return 0
}

var File_pkg_structures_schedule_schedule_proto protoreflect.FileDescriptor

var file_pkg_structures_schedule_schedule_proto_rawDesc = string([]byte{
	0x0a, 0x26, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x22, 0x41, 0x0a, 0x10, 0x67, 0x63, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x73, 0x22, 0x51, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d,
	0x61, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x28,
	0x0a, 0x05, 0x53, 0x63, 0x68, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x05, 0x53, 0x63, 0x68, 0x65, 0x64, 0x22, 0x6e, 0x0a, 0x08, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x47, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x79,
	0x63, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x67, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x2d, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x3f, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x66, 0x66,
	0x69, 0x63, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x66, 0x66,
	0x69, 0x63, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x0f, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63,
	0x2d, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x66,
	0x66, 0x69, 0x63, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x0f,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x50, 0x6f, 0x72, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x2d,
	0x70, 0x6f, 0x72, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pkg_structures_schedule_schedule_proto_rawDescOnce sync.Once
	file_pkg_structures_schedule_schedule_proto_rawDescData []byte
)

func file_pkg_structures_schedule_schedule_proto_rawDescGZIP() []byte {
	file_pkg_structures_schedule_schedule_proto_rawDescOnce.Do(func() {
		file_pkg_structures_schedule_schedule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_structures_schedule_schedule_proto_rawDesc), len(file_pkg_structures_schedule_schedule_proto_rawDesc)))
	})
	return file_pkg_structures_schedule_schedule_proto_rawDescData
}

var file_pkg_structures_schedule_schedule_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_structures_schedule_schedule_proto_goTypes = []any{
	(*GclConfiguration)(nil), // 0: schedule.gclConfiguration
	(*ConfigMap)(nil),        // 1: schedule.ConfigMap
	(*Schedule)(nil),         // 2: schedule.schedule
	(*TrafficClass)(nil),     // 3: schedule.TrafficClass
}
var file_pkg_structures_schedule_schedule_proto_depIdxs = []int32{
	1, // 0: schedule.gclConfiguration.configs:type_name -> schedule.ConfigMap
	2, // 1: schedule.ConfigMap.Sched:type_name -> schedule.schedule
	3, // 2: schedule.schedule.TrafficClasses:type_name -> schedule.TrafficClass
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_structures_schedule_schedule_proto_init() }
func file_pkg_structures_schedule_schedule_proto_init() {
	if File_pkg_structures_schedule_schedule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_structures_schedule_schedule_proto_rawDesc), len(file_pkg_structures_schedule_schedule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_structures_schedule_schedule_proto_goTypes,
		DependencyIndexes: file_pkg_structures_schedule_schedule_proto_depIdxs,
		MessageInfos:      file_pkg_structures_schedule_schedule_proto_msgTypes,
	}.Build()
	File_pkg_structures_schedule_schedule_proto = out.File
	file_pkg_structures_schedule_schedule_proto_goTypes = nil
	file_pkg_structures_schedule_schedule_proto_depIdxs = nil
}
